services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

  mongodb:
      image: mongo:latest
      container_name: url_shortener_mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
        MONGO_INITDB_DATABASE: url_shortener
      ports:
        - "27017:27017"
      restart: always
      volumes:
        - ./mongodb_data:/data/db

volumes:
  mongodb_data:
